#!/bin/bash

deactivate 2>/dev/null
echo 'Creating Virtual Environment'
python installation/setup.py > webmote-env.py
python webmote-env.py webmote-env
rm webmote-env.py

cp -a utils/* .
echo "Webmote needs your permission to communicate with USB devices"
sudo usermod -a -G tty $(logname)
sudo usermod -a -G dialout $(logname)
